on:
  pull_request:
    types: [opened]

jobs:
    test:
      runs-on: ubuntu-latest
      steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Nodejs
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Unit test
        run: |
          node -v
          npm install
          cp config.json.example config.json
          npm test